# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.1.3-10-g1536ecf
_src_path: git@git.sr.ht:~dmerej/copier-python
author_email: dimitri.merejkowsky@arolla.fr
author_name: Dimitri Merejkowsky
package_import_name: todo_list
project_description: Using DDD with Django on a simple TODO-list app
project_name: todo-list
project_version: 0.0.1

